# Generated by Django 3.2b1 on 2021-03-18 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyyy', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1989), django.core.validators.MaxValueValidator(2099)], verbose_name='年')),
                ('mm', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('dd', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('debit_account_id', models.IntegerField(verbose_name='科目コード(借方)')),
                ('credit_account_id', models.IntegerField(verbose_name='科目コード(貸方)')),
                ('money', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)], verbose_name='金額')),
                ('summary', models.CharField(default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '仕訳帳',
                'db_table': 'fsjs_journals',
            },
        ),
    ]
