# Generated by Django 3.2b1 on 2021-03-21 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='名前')),
                ('email', models.EmailField(max_length=250, unique=True, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=250, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='パスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ユーザー',
                'db_table': 'fsjs_users',
            },
        ),
    ]
